import type { Metadata } from 'next';
import { Almarai } from 'next/font/google';
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';
import { AuthProvider } from '@/components/AuthProvider/AuthProvider';
import { getServerUser } from '@/services/authServer';
import './global.scss';

const almarai = Almarai({
  variable: '--font-almarai',
  weight: ['400', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const user = await getServerUser();
  return (
    <html lang="en" className={`${almarai.variable}`}>
      <body className="wrapper">
        <Header />
        <AuthProvider user={user}>
          <main className="main-content">{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
